language: node_js
node_js:
  - stable

sudo: false

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --browsers=Firefox
  - codeclimate-test-reporter < coverage/*/lcov.info

addons:
    firefox: latest
    code_climate:
        repo_token: 65e8dbb60c4122ae34a35bc6d312a3d0d16984cbf78e6fc8267c7e52f82d40bc